// projeto-vue/src/App.vue
<template>
  <div>
    <!-- Formulário -->
    <form @submit.prevent="cadastrar">
      <input type="text" v-model="nome" placeholder="Nome">
      <input type="text" v-model="idade" placeholder="Idade">
      <button type="submit">Cadastrar</button>
    </form>

    <!-- Tabela -->
    <table border="1">
      <thead>
        <tr>
          <th>Nome</th>
          <th>Idade</th>
        </tr>
      </thead>
      <tbody>
        <tr v-for="(registro, index) in registros" :key="index">
          <td>{{ registro.nome }}</td>
          <td>{{ registro.idade }}</td>
        </tr>
      </tbody>
    </table>
  </div>
</template>

<script>
export default {
  data() {
    return {
      registros: [],
      nome: '',
      idade: ''
    };
  },
  mounted() {
    this.obterRegistros();
  },
  methods: {
    obterRegistros() {
      fetch('http://localhost:8080')
        .then(response => response.json())
        .then(data => {
          this.registros = data;
        })
        .catch(error => {
          console.error('Erro ao obter registros:', error);
        });
    },
    cadastrar() {
      const pessoa = { nome: this.nome, idade: parseInt(this.idade) };

      fetch('http://localhost:8080', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json'
        },
        body: JSON.stringify(pessoa)
      })
        .then(response => response.json())
        .then(data => {
          this.registros.push(data);
          this.nome = '';
          this.idade = '';
        })
        .catch(error => {
          console.error('Erro ao cadastrar pessoa:', error);
        });
    }
  }
};
</script>

// projeto-react/src/App.js
import React, { useState, useEffect } from 'react';

function App() {
  const [registros, setRegistros] = useState([]);
  const [nome, setNome] = useState('');
  const [idade, setIdade] = useState('');

  // Função para obter todos os registros da API
  const obterRegistros = () => {
    fetch('http://localhost:8080')
      .then(response => response.json())
      .then(data => setRegistros(data))
      .catch(error => console.error('Erro ao obter registros:', error));
  };

  // Função para cadastrar uma pessoa na API
  const cadastrar = () => {
    const pessoa = { nome, idade };

    fetch('http://localhost:8080', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify(pessoa)
    })
      .then(response => response.json())
      .then(data => {
        setRegistros([...registros, data]);
        setNome('');
        setIdade('');
      })
      .catch(error => console.error('Erro ao cadastrar pessoa:', error));
  };

  useEffect(() => {
    obterRegistros();
  }, []); // Executa apenas uma vez no carregamento inicial

  return (
    <div>
      {/* Formulário */}
      <form>
        <input
          type="text"
          placeholder="Nome"
          value={nome}
          onChange={e => setNome(e.target.value)}
        />
        <input
          type="text"
          placeholder="Idade"
          value={idade}
          onChange={e => setIdade(e.target.value)}
        />
        <button type="button" onClick={cadastrar}>
          Cadastrar
        </button>
      </form>

      {/* Tabela */}
      <table border="1">
        <thead>
          <tr>
            <th>Nome</th>
            <th>Idade</th>
          </tr>
        </thead>
        <tbody>
          {registros.map((registro, index) => (
            <tr key={index}>
              <td>{registro.nome}</td>
              <td>{registro.idade}</td>
            </tr>
          ))}
        </tbody>
      </table>
    </div>
  );
}

export default App;
